$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$script=Join-Path $root 'scripts\protect-gbuzz-secrets.ps1'
function Throws([scriptblock]$Action,[string]$Message){$ok=$false;try{&$Action}catch{if($_.Exception.Message-notmatch[regex]::Escape($Message)){throw};$ok=$true};if(-not$ok){throw "Expected failure containing: $Message"}}
$scratch=Join-Path ([IO.Path]::GetTempPath()) ('gbuzz-acl-behavior-'+[guid]::NewGuid().ToString('n'));New-Item -ItemType Directory $scratch|Out-Null
$secret=Join-Path $scratch 'secret.txt';$second=Join-Path $scratch 'second.txt';$audit=Join-Path $scratch 'audit';$keyPath=Join-Path $scratch 'rollback.key';$config=Join-Path $scratch 'protected.json';New-Item -ItemType Directory $audit|Out-Null;Set-Content $secret synthetic;Set-Content $second synthetic;$key=New-Object byte[] 32;[Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($key);[IO.File]::WriteAllBytes($keyPath,$key);@{schema_version=1;rollback_mac_key_path=$keyPath;rollback_mac_key_sha256=(Get-FileHash $keyPath -Algorithm SHA256).Hash.ToLowerInvariant()}|ConvertTo-Json|Set-Content $config
$identity=[Security.Principal.WindowsIdentity]::GetCurrent().Name;$before=@{};foreach($p in @($secret,$second,$audit)){$before[$p]=(Microsoft.PowerShell.Security\Get-Acl -LiteralPath $p).GetSecurityDescriptorSddlForm([Security.AccessControl.AccessControlSections]::Access)}
try{
  # Config/key protection is modeled as an already owner-protected external prerequisite; target DACLs remain real disposable files.
  $global:badAclMode='';function global:Get-Acl { param([string]$LiteralPath);if($LiteralPath-in@($config,$keyPath)){if($global:badAclMode-eq'inherit'){return [pscustomobject]@{AreAccessRulesProtected=$false;Access=@()}};if($global:badAclMode-eq'identity'){return [pscustomobject]@{AreAccessRulesProtected=$true;Access=@([pscustomobject]@{AccessControlType='Allow';IdentityReference=[Security.Principal.NTAccount]::new($identity)})}};return [pscustomobject]@{AreAccessRulesProtected=$true;Access=@()}}else{Microsoft.PowerShell.Security\Get-Acl -LiteralPath $LiteralPath} }
  $global:badAclMode='inherit';Throws {& $script -Mode Apply -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -Confirm:$false} 'must not inherit';$global:badAclMode='identity';Throws {& $script -Mode Apply -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -Confirm:$false} 'unapproved owner/ACL';$global:badAclMode=''
  $result=& $script -Mode Apply -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -Confirm:$false|ConvertFrom-Json
  Throws {& $script -Mode Rollback -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -RollbackManifest $result.rollback_manifest -ExpectedRunId wrong -ExpectedOperation restrict-secret-acls -Confirm:$false} 'another run'
  Throws {& $script -Mode Rollback -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -RollbackManifest $result.rollback_manifest -ExpectedRunId $result.run_id -ExpectedOperation wrong-operation -Confirm:$false} 'another run'
  # Changed key digest and weak key fail before any restore.
  [IO.File]::WriteAllBytes($keyPath,(New-Object byte[] 16));Throws {& $script -Mode Rollback -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -RollbackManifest $result.rollback_manifest -ExpectedRunId $result.run_id -Confirm:$false} 'at least 32 bytes';[IO.File]::WriteAllBytes($keyPath,$key)
  $changed=[byte[]]$key.Clone();$changed[0]=$changed[0]-bxor1;[IO.File]::WriteAllBytes($keyPath,$changed);Throws {& $script -Mode Rollback -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -RollbackManifest $result.rollback_manifest -ExpectedRunId $result.run_id -Confirm:$false} 'key identity mismatch';[IO.File]::WriteAllBytes($keyPath,$key)
  & $script -Mode Rollback -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -RollbackManifest $result.rollback_manifest -ExpectedRunId $result.run_id -ExpectedOperation restrict-secret-acls -Confirm:$false
  foreach($p in @($secret,$second,$audit)){if((Microsoft.PowerShell.Security\Get-Acl -LiteralPath $p).GetSecurityDescriptorSddlForm([Security.AccessControl.AccessControlSections]::Access)-ne$before[$p]){throw "Full transaction did not restore $p"}}
  # Deterministically replace the stable identity at the last target after earlier targets mutate.
  $realFsutil=Join-Path $env:SystemRoot 'System32\fsutil.exe';$global:idCalls=@{};$global:replacePath=$secret
  function global:fsutil { $argv=@($args);$out=& $realFsutil @argv;if($argv.Count-ge3-and$argv[0]-eq'file'-and$argv[1]-eq'queryfileid'){$p=[string]$argv[2];$global:idCalls[$p]=1+[int]$global:idCalls[$p];if($p-eq$global:replacePath-and$global:idCalls[$p]-eq2){return 'File ID is 0x000000000000000000000000deadbeef'}};$out }
  Throws {& $script -Mode Apply -OperatingIdentity $identity -SecretPaths @($secret,$second) -EvidenceRoot $audit -ProtectedConfiguration $config -Confirm:$false} 'Stable file identity changed during operation'
  Remove-Item function:\fsutil -ErrorAction SilentlyContinue
  foreach($p in @($secret,$second,$audit)){if((Microsoft.PowerShell.Security\Get-Acl -LiteralPath $p).GetSecurityDescriptorSddlForm([Security.AccessControl.AccessControlSections]::Access)-ne$before[$p]){throw "Injected identity failure did not restore and reverify $p"}}
  # Real hard-link identity is rejected in Audit mode without changing ACLs.
  $link=Join-Path $scratch 'linked.txt';fsutil hardlink create $link $secret|Out-Null;Throws {& $script -Mode Audit -OperatingIdentity $identity -SecretPaths $secret -EvidenceRoot $audit} 'Hard-linked secret path rejected';Remove-Item $link -Force
  # Parent reparse traversal is rejected using a real directory junction.
  $target=Join-Path $scratch 'target';$junction=Join-Path $scratch 'junction';New-Item -ItemType Directory $target|Out-Null;Set-Content (Join-Path $target 'nested.txt') x;New-Item -ItemType Junction -Path $junction -Target $target|Out-Null;Throws {& $script -Mode Audit -OperatingIdentity $identity -SecretPaths (Join-Path $junction 'nested.txt') -EvidenceRoot $audit} 'Reparse-point path component rejected';[IO.Directory]::Delete($junction)
}finally{Remove-Item function:\Get-Acl,function:\fsutil -ErrorAction SilentlyContinue;foreach($p in @($secret,$second,$audit)){if(Test-Path $p){try{$a=Microsoft.PowerShell.Security\Get-Acl -LiteralPath $p;$a.SetSecurityDescriptorSddlForm($before[$p],[Security.AccessControl.AccessControlSections]::Access);if((Get-Item $p)-is[IO.DirectoryInfo]){[IO.Directory]::SetAccessControl($p,$a)}else{[IO.File]::SetAccessControl($p,$a)}}catch{}}};Remove-Item $scratch -Recurse -Force -ErrorAction SilentlyContinue}
Write-Output 'LAN ACL behavioral negatives passed.'
