$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$script=Join-Path $root 'scripts\new-release-security-evidence.ps1'
function Throws([scriptblock]$Action,[string]$Message){$ok=$false;try{&$Action}catch{if($_.Exception.Message-notmatch[regex]::Escape($Message)){throw};$ok=$true};if(-not$ok){throw "Expected failure containing: $Message"}}
function Sign($rsa,$payload,[string]$KeyId){$bytes=[Text.Encoding]::UTF8.GetBytes(($payload|ConvertTo-Json -Depth 20 -Compress));[ordered]@{key_id=$KeyId;payload_b64=[Convert]::ToBase64String($bytes);signature_b64=[Convert]::ToBase64String($rsa.SignData($bytes,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1))}}
function PublicKey($rsa,[string]$KeyId,[int]$Bits){$p=$rsa.ExportParameters($false);[ordered]@{key_id=$KeyId;algorithm='RS256';bits=$Bits;revoked=$false;modulus_b64=[Convert]::ToBase64String($p.Modulus);exponent_b64=[Convert]::ToBase64String($p.Exponent)}}
$scratch=Join-Path ([IO.Path]::GetTempPath()) ('gbuzz-release-'+[guid]::NewGuid().ToString('n'));New-Item -ItemType Directory $scratch|Out-Null
$realGetAcl=(Get-Command Get-Acl -CommandType Cmdlet)
try{
  # Mock only the ACL read adapter. Files and Git repository are real disposable user-mode fixtures.
  function global:Get-Acl { param([string]$LiteralPath);[pscustomobject]@{AreAccessRulesProtected=$true;Access=@()} }
  $repo=Join-Path $scratch 'repo';New-Item -ItemType Directory $repo|Out-Null;git -C $repo init -b approved|Out-Null;git -C $repo config user.name test;git -C $repo config user.email test@example.invalid;Set-Content "$repo/file.txt" x;git -C $repo add file.txt;git -C $repo commit -m init|Out-Null;git -C $repo remote add origin https://example.invalid/approved.git;$commit=(git -C $repo rev-parse HEAD).Trim()
  $digestA='a'*64;$digestB='b'*64;$imageA="registry/a@sha256:$digestA";$imageB="registry/b@sha256:$digestB";@{services=@{relay=@{image=$imageA}}}|ConvertTo-Json -Depth 4|Set-Content "$scratch/compose.json";Set-Content "$scratch/images.txt" $imageB
  function Write-Sbom($digests){@{spdxVersion='SPDX-2.3';SPDXID='SPDXRef-DOCUMENT';packages=@($digests|%{@{externalRefs=@(@{referenceType='gitoid';referenceLocator=('sha256:'+$_)})}})}|ConvertTo-Json -Depth 8|Set-Content "$scratch/sbom.json"}
  function Run([array]$digests=@($digestA,$digestB),[string]$scanner='approved-scanner',[string]$severity='none',[string]$exception=''){@{version='2.1.0';runs=@($digests|%{@{tool=@{driver=@{name=$scanner;version='1'}};invocations=@(@{executionSuccessful=$true});properties=@{targetDigest=$_};results=@($(if($severity-ne'none'){@{properties=@{normalizedSeverity=$severity;exceptionId=$exception};suppressions=@(@{kind='external'})}}))}})}|ConvertTo-Json -Depth 10|Set-Content "$scratch/scan.json"}
  $owner=[Security.Cryptography.RSA]::Create(3072);$release=[Security.Cryptography.RSA]::Create(3072);$material='c'*64
  $statement=[ordered]@{repository_root=$repo;source_repository_uri='https://example.invalid/approved.git';permitted_ref='approved';scanner=@{name='approved-scanner';version='1'};approved_exception_ids=@('CVE-APPROVED');signature_identity='release@example.invalid';signature_issuer='issuer';allowed_builder_ids=@('builder');required_materials=@(@{uri='git+https://example.invalid/approved.git';sha256=$material});release_keys=@((PublicKey $release 'release' 3072))}
  function Write-Policy([datetimeoffset]$From=([DateTimeOffset]::UtcNow.AddHours(-1)),[datetimeoffset]$Until=([DateTimeOffset]::UtcNow.AddHours(1)),[bool]$Revoked=$false,[int]$OwnerBits=3072){$policy=[ordered]@{policy_id='approved';version='1';signer_key_id='owner';valid_from=$From.ToString('o');valid_until=$Until.ToString('o');revoked=$Revoked;statement=$statement;signature=(Sign $owner $statement 'owner')};$policy|ConvertTo-Json -Depth 20|Set-Content "$scratch/policy.json";$config=[ordered]@{schema_version=1;approved_root=$scratch;approved_deployment_root=$scratch;owner_keys=@((PublicKey $owner 'owner' $OwnerBits));policies=@(@{policy_id='approved';version='1';signer_key_id='owner';path="$scratch/policy.json";sha256=(Get-FileHash "$scratch/policy.json" -Algorithm SHA256).Hash.ToLowerInvariant()})};$config|ConvertTo-Json -Depth 20|Set-Content "$scratch/config.json"}
  function Write-SignedEvidence([string]$Builder='builder',[string]$MaterialUri='git+https://example.invalid/approved.git'){ @((Sign $release ([ordered]@{kind='image-signature';image=$imageA;identity='release@example.invalid';issuer='issuer'}) 'release'),(Sign $release ([ordered]@{kind='image-signature';image=$imageB;identity='release@example.invalid';issuer='issuer'}) 'release'))|ConvertTo-Json -Depth 10|Set-Content "$scratch/signatures.json";@((Sign $release ([ordered]@{kind='slsa-provenance';image=$imageA;subject_sha256=$digestA;source_commit=$commit;source_repository_uri='https://example.invalid/approved.git';builder_id=$Builder;materials=@(@{uri=$MaterialUri;digest=@{sha256=$material}})}) 'release'),(Sign $release ([ordered]@{kind='slsa-provenance';image=$imageB;subject_sha256=$digestB;source_commit=$commit;source_repository_uri='https://example.invalid/approved.git';builder_id=$Builder;materials=@(@{uri=$MaterialUri;digest=@{sha256=$material}})}) 'release'))|ConvertTo-Json -Depth 12|Set-Content "$scratch/provenance.json"}
  $invoke=@{ResolvedComposeJson="$scratch/compose.json";BuildImageManifest="$scratch/images.txt";SbomPath="$scratch/sbom.json";VulnerabilitySarif="$scratch/scan.json";SignatureReport="$scratch/signatures.json";ProvenanceReport="$scratch/provenance.json";PolicyId='approved';ProtectedConfiguration="$scratch/config.json";OutputPath="$scratch/out.json"}
  Write-Sbom @($digestA,$digestB);Run;Write-Policy;Write-SignedEvidence;& $script @invoke|Out-Null
  Write-Sbom @($digestA);Throws {& $script @invoke} 'SBOM digest coverage';Write-Sbom @($digestA,$digestB,$digestB);Throws {& $script @invoke} 'SBOM digest coverage';Write-Sbom @($digestA,$digestB)
  Run @($digestA);Throws {& $script @invoke} 'Scan digest coverage';Run @($digestA,$digestB,$digestB);Throws {& $script @invoke} 'Scan digest coverage';Run @($digestA,$digestB) 'wrong';Throws {& $script @invoke} 'Unsupported or incomplete scanner';Run @($digestA,$digestB) 'approved-scanner' 'mystery';Throws {& $script @invoke} 'Unknown normalized';Run @($digestA,$digestB) 'approved-scanner' 'high' 'NOPE';Throws {& $script @invoke} 'Unapproved HIGH/CRITICAL';Run
  Write-SignedEvidence 'wrong';Throws {& $script @invoke} 'Provenance identity mismatch';Write-SignedEvidence 'builder' 'git+https://example.invalid/wrong.git';Throws {& $script @invoke} 'Provenance material set mismatch';Write-SignedEvidence
  Write-Policy ([DateTimeOffset]::UtcNow.AddDays(-2)) ([DateTimeOffset]::UtcNow.AddDays(-1));Throws {& $script @invoke} 'expired, premature, or revoked';Write-Policy ([DateTimeOffset]::UtcNow.AddHours(-1)) ([DateTimeOffset]::UtcNow.AddHours(1)) $true;Throws {& $script @invoke} 'expired, premature, or revoked';Write-Policy ([DateTimeOffset]::UtcNow.AddHours(-1)) ([DateTimeOffset]::UtcNow.AddHours(1)) $false 2048;Throws {& $script @invoke} 'algorithm/strength';Write-Policy
  Add-Content "$scratch/policy.json" ' ';Throws {& $script @invoke} 'Approved policy digest mismatch';Write-Policy
  $statement.permitted_ref='wrong';Write-Policy;Throws {& $script @invoke} 'Source ref is not permitted';$statement.permitted_ref='approved';$statement.repository_root=Join-Path $scratch 'wrong';Write-Policy;Throws {& $script @invoke} 'Cannot find path';$statement.repository_root=$repo;Write-Policy
}finally{Remove-Item function:\Get-Acl -ErrorAction SilentlyContinue;$owner.Dispose();$release.Dispose();Remove-Item $scratch -Recurse -Force -ErrorAction SilentlyContinue}
Write-Output 'Release evidence behavioral negatives passed.'
