$ErrorActionPreference='Stop';Set-ExecutionPolicy -Scope Process Bypass -Force
$root=Split-Path -Parent $PSScriptRoot;$scratch=Join-Path ([IO.Path]::GetTempPath()) ('gbuzz-reliability-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $scratch|Out-Null
function Assert-Throws([scriptblock]$Action,[string]$Expected){$threw=$false;try{&$Action}catch{$threw=$true;if($_.Exception.Message-notmatch$Expected){throw}};if(-not$threw){throw "Expected failure matching $Expected"}}
try{
    Import-Module (Join-Path $root 'scripts\ComposePlan.psm1') -Force;$repo=Join-Path $scratch 'repo';New-Item -ItemType Directory $repo|Out-Null;@('docker-compose.yml','docker-compose.safeguards.override.json')|ForEach-Object{Set-Content (Join-Path $repo $_) 'services: {}'}
    $wrong=Join-Path $scratch 'wrong.json';@{project='gbuzz';files=@('docker-compose.yml','docker-compose.graph.yml');profiles=@();required_services=@()}|ConvertTo-Json|Set-Content $wrong;Assert-Throws {Get-GbuzzComposePlan $repo $wrong} 'missing|graph'
    $missing=Join-Path $scratch 'missing.json';@{project='gbuzz';files=@('docker-compose.yml','docker-compose.safeguards.override.json','missing.yml');profiles=@();required_services=@()}|ConvertTo-Json|Set-Content $missing;Assert-Throws {Get-GbuzzComposePlan $repo $missing} 'missing'
    $required=Join-Path $scratch 'required.json';@{project='gbuzz';files=@('docker-compose.yml','docker-compose.safeguards.override.json');profiles=@();required_services=@('postgres','minio')}|ConvertTo-Json|Set-Content $required;$requiredPlan=Get-GbuzzComposePlan $repo $required;Assert-Throws {Assert-GbuzzRequiredServices $requiredPlan ([pscustomobject]@{services=[pscustomobject]@{postgres=[pscustomobject]@{}}})} 'missing required services: minio'
    $backupRoot=Join-Path $scratch 'retention';New-Item -ItemType Directory $backupRoot|Out-Null;foreach($offset in @(0,6)){$time=[datetime]::UtcNow.AddHours(-$offset);$dir=Join-Path $backupRoot ($time.ToString('yyyyMMddTHHmmssZ')+'-'+('a'*8));New-Item -ItemType Directory $dir|Out-Null;New-Item -ItemType File (Join-Path $dir 'COMPLETE')|Out-Null;[IO.File]::WriteAllBytes((Join-Path $dir 'payload.gbuzzenc'),(New-Object byte[] 100))};Assert-Throws {& (Join-Path $root 'scripts\prune-backups.ps1') -BackupRoot $backupRoot -MaxLocalBytes 150} 'protected recovery points were not deleted';if((Get-ChildItem $backupRoot -Directory).Count-ne 2){throw 'Protected retention point was deleted.'}
    $valid=Join-Path $scratch 'valid.json';@{project='gbuzz';files=@('docker-compose.yml','docker-compose.safeguards.override.json');profiles=@();required_services=@()}|ConvertTo-Json|Set-Content $valid;$key=New-Object byte[] 64;$rng=[Security.Cryptography.RandomNumberGenerator]::Create();$rng.GetBytes($key);$rng.Dispose();$env:GBUZZ_BACKUP_KEY_BASE64=[Convert]::ToBase64String($key);$env:GBUZZ_BACKUP_TEST_MODE='1';$partial=Join-Path $scratch 'partial';$metrics=Join-Path $scratch 'metrics\backup.prom';Assert-Throws {& (Join-Path $root 'scripts\backup-stack.ps1') -RepoRoot $repo -ConfigPath $valid -BackupRoot $partial -MetricsPath $metrics -TestFailAfterComponent initialized} 'Injected failure';if(Get-ChildItem $partial -Directory -Filter '.incomplete-*' -ErrorAction SilentlyContinue){throw 'Partial backup staging was not cleaned.'}
    Write-Output 'reliability-powershell-tests: ok'
}finally{Remove-Item -LiteralPath $scratch -Recurse -Force -ErrorAction SilentlyContinue;$env:GBUZZ_BACKUP_TEST_MODE=$null;$env:GBUZZ_BACKUP_KEY_BASE64=$null}
