$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$script=Join-Path $root 'scripts\configure-gbuzz-lan-boundary.ps1'
function Throws([scriptblock]$Action,[string]$Message){$ok=$false;try{&$Action}catch{if($_.Exception.Message-notmatch[regex]::Escape($Message)){throw};$ok=$true};if(-not$ok){throw "Expected failure containing: $Message"}}
function Rule([string]$Description='prior',[string]$Direction='Inbound',[string]$Action='Block',[string]$Enabled='True',[string]$Profile='Private',[string]$Protocol='TCP',[string]$LocalPort='3000',[string]$RemotePort='Any',[string[]]$LocalAddress=@('192.168.1.10'),[string[]]$RemoteAddress=@('192.168.1.0/24')){[pscustomobject]@{DisplayName='Gbuzz Relay - approved LAN only';Description=$Description;Direction=$Direction;Action=$Action;Enabled=$Enabled;Profile=$Profile;PolicyStoreSourceType='Local';Protocol=$Protocol;LocalPort=$LocalPort;RemotePort=$RemotePort;LocalAddress=$LocalAddress;RemoteAddress=$RemoteAddress}}
$global:fwRules=@();$global:restoreMutation=$null
function global:Get-NetIPAddress {[pscustomobject]@{IPAddress='192.168.1.10'}}
function global:Get-NetFirewallRule { @($global:fwRules) }
function global:Get-NetFirewallPortFilter { process { [pscustomobject]@{Protocol=$_.Protocol;LocalPort=$_.LocalPort;RemotePort=$_.RemotePort} } }
function global:Get-NetFirewallAddressFilter { process { [pscustomobject]@{LocalAddress=$_.LocalAddress;RemoteAddress=$_.RemoteAddress} } }
function global:Get-NetNatStaticMapping { @() }
function global:Get-Process { @() }
function global:netsh { @() }
function global:Remove-NetFirewallRule { process {$global:fwRules=@($global:fwRules|Where-Object{$_-ne$_})} }
function global:New-NetFirewallRule {
  param($DisplayName,$Description,$Direction,$Action,$Enabled='True',$Profile,$Protocol,$LocalPort,$RemotePort='Any',$LocalAddress,$RemoteAddress)
  $r=Rule -Description $Description -Direction $Direction -Action $Action -Enabled $Enabled -Profile $Profile -Protocol $Protocol -LocalPort $LocalPort -RemotePort $RemotePort -LocalAddress @($LocalAddress) -RemoteAddress @($RemoteAddress)
  if($global:restoreMutation){$r.($global:restoreMutation.field)=$global:restoreMutation.value};$global:fwRules+=,$r;$r
}
try{
  $tmp=Join-Path ([IO.Path]::GetTempPath()) ('gbuzz-fw-'+[guid]::NewGuid().ToString('n'));New-Item -ItemType Directory $tmp|Out-Null
  $prior=Rule;$snapshot=@([ordered]@{display_name=$prior.DisplayName;description=$prior.Description;direction=$prior.Direction;action=$prior.Action;enabled=$prior.Enabled;profile=@($prior.Profile);protocol=$prior.Protocol;local_port=@($prior.LocalPort);remote_port=@($prior.RemotePort);local_address=@($prior.LocalAddress);remote_address=@($prior.RemoteAddress)});$snapshot|ConvertTo-Json -Depth 6|Set-Content "$tmp/prior.json"
  # Explicit rollback restores the complete prior rule and verifies final state.
  $global:fwRules=@(Rule -Description 'managed' -Action 'Allow');& $script -Mode Rollback -BindAddress 192.168.1.10 -RemoteCidr 192.168.1.0/24 -ExpectedRollbackSnapshot "$tmp/prior.json" -Confirm:$false
  if($global:fwRules.Count-ne1-or$global:fwRules[0].Description-ne'prior'-or$global:fwRules[0].Action-ne'Block'){throw 'Explicit rollback final state mismatch'}
  # A field mutation during restore fails critically after comparing final state.
  $global:fwRules=@(Rule -Description 'managed' -Action 'Allow');$global:restoreMutation=@{field='RemoteAddress';value=@('Any')};Throws {& $script -Mode Rollback -BindAddress 192.168.1.10 -RemoteCidr 192.168.1.0/24 -ExpectedRollbackSnapshot "$tmp/prior.json" -Confirm:$false} 'explicit rollback verification failed';$global:restoreMutation=$null
  if($global:fwRules[0].RemoteAddress-ne'Any'){throw 'Injected partial restore final state was not observed'}
  # Missing evidence remains non-compliant despite a locally compliant rule.
  $global:fwRules=@(Rule -Action 'Allow' -Description '');$audit=& $script -Mode Audit -BindAddress 192.168.1.10 -RemoteCidr 192.168.1.0/24|ConvertFrom-Json;if($audit.compliant-ne$false-or$audit.effective_path_and_routed_client_proof-ne$false){throw 'Missing routed evidence did not fail closed'}
  function global:Get-Acl { [pscustomobject]@{AreAccessRulesProtected=$true;Access=@()} }
  function Payload($p){[ordered]@{schema_version=$p.schema_version;evidence_type=$p.evidence_type;evidence_mode=$p.evidence_mode;probe_role=$p.probe_role;key_id=$p.key_id;probe_identity=$p.probe_identity;probe_host=$p.probe_host;observed_source_address=$p.observed_source_address;relay_address=$p.relay_address;port=$p.port;approved_cidr=$p.approved_cidr;expected_reachable=$p.expected_reachable;actual_reachable=$p.actual_reachable;passed=$p.passed;protocol=$p.protocol;deployment_id=$p.deployment_id;release_id=$p.release_id;compose_digest=$p.compose_digest;firewall_policy_digest=$p.firewall_policy_digest;run_id=$p.run_id;nonce=$p.nonce;started_at=$p.started_at;ended_at=$p.ended_at;tool=$p.tool;tool_version=$p.tool_version;error=$p.error}|ConvertTo-Json -Compress}
  function Pub($rsa,[string]$id,[string]$role){$x=$rsa.ExportParameters($false);@{key_id=$id;probe_role=$role;algorithm='RS256';bits=3072;revoked=$false;modulus_b64=[Convert]::ToBase64String($x.Modulus);exponent_b64=[Convert]::ToBase64String($x.Exponent)}}
  function Sign($p,$rsa){$p.signature_b64=[Convert]::ToBase64String($rsa.SignData([Text.Encoding]::UTF8.GetBytes((Payload $p)),[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1))}
  $aKey=[Security.Cryptography.RSA]::Create(3072);$dKey=[Security.Cryptography.RSA]::Create(3072);$now=[DateTimeOffset]::UtcNow;$compose='c'*64;$firewall='f'*64
  @{schema_version=2;approved_root=$tmp;deployment_id='deploy';release_id='release';compose_digest=$compose;firewall_policy_digest=$firewall;run_id='run';nonce='nonce';max_age_minutes=10;gbuzz_host_identity='gbuzz-host';probe_keys=@((Pub $aKey 'allowed-key' 'allowed_client'),(Pub $dKey 'denied-key' 'excluded_client'))}|ConvertTo-Json -Depth 10|Set-Content "$tmp/policy.json"
  function New-Proof([string]$role,[string]$key,[string]$identity,[string]$ProbeHost,[string]$source,[bool]$reachable){[ordered]@{schema_version=1;evidence_type='gbuzz-lan-reachability';evidence_mode='activation_probe';probe_role=$role;key_id=$key;probe_identity=$identity;probe_host=$ProbeHost;observed_source_address=$source;relay_address='192.168.1.10';port=3000;approved_cidr='192.168.1.0/24';expected_reachable=$reachable;actual_reachable=$reachable;passed=$true;protocol='tcp';deployment_id='deploy';release_id='release';compose_digest=$compose;firewall_policy_digest=$firewall;run_id='run';nonce='nonce';started_at=$now.AddMinutes(-1).ToString('o');ended_at=$now.ToString('o');tool='external-probe';tool_version='1';error=''}}
  $allowed=New-Proof 'allowed_client' 'allowed-key' 'allowed-id' 'allowed-host' '192.168.1.20' $true;$denied=New-Proof 'excluded_client' 'denied-key' 'denied-id' 'denied-host' '10.0.0.20' $false;Sign $allowed $aKey;Sign $denied $dKey
  function Write-Proofs($x=$allowed,$y=$denied){$x|ConvertTo-Json -Depth 8|Set-Content "$tmp/allowed.json";$y|ConvertTo-Json -Depth 8|Set-Content "$tmp/denied.json"}
  function Audit(){& $script -Mode Audit -BindAddress 192.168.1.10 -RemoteCidr 192.168.1.0/24 -ExposureEvidencePolicy "$tmp/policy.json" -EffectivePathEvidence "$tmp/allowed.json" -RoutedClientEvidence "$tmp/denied.json"|ConvertFrom-Json}
  Write-Proofs;if((Audit).compliant-ne$true){throw 'Valid activation proofs were rejected'}
  $cases=@(@('evidence_mode','modeled_test'),@('deployment_id','wrong'),@('release_id','wrong'),@('compose_digest',('0'*64)),@('firewall_policy_digest',('0'*64)),@('run_id','other'),@('nonce','other'),@('relay_address','192.168.1.11'),@('port',3001),@('approved_cidr','192.168.2.0/24'),@('protocol','udp'),@('passed',$false),@('actual_reachable',$false),@('observed_source_address','10.0.0.2'),@('probe_host','gbuzz-host'))
  foreach($case in $cases){$bad=$allowed.PSObject.Copy();$bad.($case[0])=$case[1];Sign $bad $aKey;Write-Proofs $bad $denied;if((Audit).compliant-ne$false){throw "Invalid proof produced compliant:true: $($case[0])"}}
  $bad=$denied.PSObject.Copy();$bad.observed_source_address='192.168.1.30';Sign $bad $dKey;Write-Proofs $allowed $bad;if((Audit).compliant-ne$false){throw 'Inside-CIDR excluded proof passed'}
  $bad=$denied.PSObject.Copy();$bad.probe_host=$allowed.probe_host;Sign $bad $dKey;Write-Proofs $allowed $bad;if((Audit).compliant-ne$false){throw 'Same-client proof passed'}
  $bad=$allowed.PSObject.Copy();$bad.ended_at=$now.AddHours(-1).ToString('o');Sign $bad $aKey;Write-Proofs $bad $denied;if((Audit).compliant-ne$false){throw 'Stale proof passed'}
  $bad=$allowed.PSObject.Copy();$bad.key_id='denied-key';Sign $bad $aKey;Write-Proofs $bad $denied;if((Audit).compliant-ne$false){throw 'Wrong key passed'}
  Write-Proofs;$allowed.signature_b64='';Write-Proofs;if((Audit).compliant-ne$false){throw 'Unsigned proof passed'};Sign $allowed $aKey;$allowed.signature_b64='AA==';Write-Proofs;if((Audit).compliant-ne$false){throw 'Wrong signature passed'};Sign $allowed $aKey
  Write-Proofs;Set-Content "$tmp/allowed.json" '';if((Audit).compliant-ne$false){throw 'Empty proof passed'};Set-Content "$tmp/allowed.json" '{}';if((Audit).compliant-ne$false){throw 'Malformed proof passed'}
  Write-Proofs;$duplicate=& $script -Mode Audit -BindAddress 192.168.1.10 -RemoteCidr 192.168.1.0/24 -ExposureEvidencePolicy "$tmp/policy.json" -EffectivePathEvidence "$tmp/allowed.json" -RoutedClientEvidence "$tmp/allowed.json"|ConvertFrom-Json;if($duplicate.compliant-ne$false){throw 'Duplicated proof passed'}
}finally{Remove-Item function:\Get-NetIPAddress,function:\Get-NetFirewallRule,function:\Get-NetFirewallPortFilter,function:\Get-NetFirewallAddressFilter,function:\Get-NetNatStaticMapping,function:\Get-Process,function:\netsh,function:\Remove-NetFirewallRule,function:\New-NetFirewallRule,function:\Get-Acl -ErrorAction SilentlyContinue;if($aKey){$aKey.Dispose()};if($dKey){$dKey.Dispose()};if($tmp){Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue}}
Write-Output 'LAN firewall behavioral negatives passed.'
