[CmdletBinding()]
param(
    [string]$RepoRoot=(Split-Path -Parent $PSScriptRoot),
    [string]$ConfigPath=(Join-Path (Split-Path -Parent $PSScriptRoot) 'config\windows-startup.compose-files.json'),
    [string]$BackupRoot='C:\ProgramData\Gbuzz\encrypted-backups',
    [string]$MetricsPath='C:\ProgramData\Gbuzz\backup-metrics\gbuzz-backup.prom',
    [long]$MaxLocalBytes=100GB,
    [ValidateSet('','initialized')][string]$TestFailAfterComponent=''
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'BackupCrypto.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'ComposePlan.psm1') -Force
$plan=Get-GbuzzComposePlan $RepoRoot $ConfigPath;$composeArgs=$plan.Arguments
$mutex=[Threading.Mutex]::new($false,'Local\GbuzzBackup');if(-not $mutex.WaitOne(0)){throw 'Another Gbuzz backup is already running.'}
$started=[DateTimeOffset]::UtcNow;$runId=$started.ToString('yyyyMMddTHHmmssZ')+'-'+[Guid]::NewGuid().ToString('N').Substring(0,8)
$work=Join-Path $BackupRoot ".incomplete-$runId";$final=Join-Path $BackupRoot $runId;$checkpoints=[Collections.Generic.List[object]]::new();$cleanupContainers=$false
function Invoke-Checked([scriptblock]$Command,[string]$Message){& $Command;if($LASTEXITCODE -ne 0){throw $Message}}
function Add-Checkpoint([string]$Component,[DateTimeOffset]$From,[string]$Detail){$checkpoints.Add([ordered]@{component=$Component;started_at=$From.ToString('o');finished_at=[DateTimeOffset]::UtcNow.ToString('o');detail=$Detail})}
function Write-Metrics([bool]$Success,[double]$Finished,[double]$Duration){$dir=Split-Path -Parent $MetricsPath;New-Item -ItemType Directory -Force $dir|Out-Null;if(-not $Success -and (Test-Path $MetricsPath)){$line=Get-Content $MetricsPath|Where-Object{$_ -match '^gbuzz_backup_last_success_unixtime '};if($line){$Finished=[double]($line-split ' ')[1]}};$tmp="$MetricsPath.tmp";@('# HELP gbuzz_backup_last_run_success Whether the most recent backup completed and verified.','# TYPE gbuzz_backup_last_run_success gauge',"gbuzz_backup_last_run_success $([int]$Success)",'# HELP gbuzz_backup_last_success_unixtime Unix time of the last successful backup.','# TYPE gbuzz_backup_last_success_unixtime gauge',"gbuzz_backup_last_success_unixtime $([int64]$Finished)",'# HELP gbuzz_backup_duration_seconds Duration of the most recent backup.','# TYPE gbuzz_backup_duration_seconds gauge',"gbuzz_backup_duration_seconds $Duration")|Set-Content -LiteralPath $tmp -Encoding ascii;Move-Item -LiteralPath $tmp -Destination $MetricsPath -Force}
try{
    Push-Location $RepoRoot
    try{$config=& docker compose @composeArgs config --format json|ConvertFrom-Json;if($LASTEXITCODE-ne 0){throw 'Unable to resolve the reviewed Compose plan.'};Assert-GbuzzRequiredServices $plan $config}finally{Pop-Location}
    & (Join-Path $PSScriptRoot 'prune-backups.ps1') -BackupRoot $BackupRoot -MaxLocalBytes $MaxLocalBytes|Out-Null
    $key=Get-BackupKey;New-Item -ItemType Directory -Force $BackupRoot,$work|Out-Null;$content=Join-Path $work 'content';New-Item -ItemType Directory $content|Out-Null
    if($TestFailAfterComponent){if($env:GBUZZ_BACKUP_TEST_MODE-ne'1'){throw 'Backup test failure injection is disabled.'};throw 'Injected failure after initialized component.'}
    Push-Location $RepoRoot
    try{
        $pgUser=$config.services.postgres.environment.POSTGRES_USER;$pgDb=$config.services.postgres.environment.POSTGRES_DB;$cleanupContainers=$true
        $mark=[DateTimeOffset]::UtcNow;Invoke-Checked {& docker compose @composeArgs exec -T postgres pg_dump -U $pgUser -d $pgDb -Fc -f /tmp/gbuzz-backup.dump} 'PostgreSQL data export failed.';Invoke-Checked {& docker compose @composeArgs cp postgres:/tmp/gbuzz-backup.dump (Join-Path $content 'postgres.dump')} 'PostgreSQL data copy failed.';Invoke-Checked {& docker compose @composeArgs exec -T postgres sh -c "pg_dumpall -U '$pgUser' --globals-only > /tmp/gbuzz-postgres-globals.sql"} 'PostgreSQL roles export failed.';Invoke-Checked {& docker compose @composeArgs cp postgres:/tmp/gbuzz-postgres-globals.sql (Join-Path $content 'postgres-globals.sql')} 'PostgreSQL roles copy failed.'
        $referenceSql="SELECT json_build_object('source','ingestion_records','id',id,'bucket',bucket,'key',object_key) FROM gcor.ingestion_records CROSS JOIN LATERAL (VALUES(original_key),(markdown_key),(record_key)) AS objects(object_key) WHERE object_key IS NOT NULL UNION ALL SELECT json_build_object('source','governance_outbox','id',event_id,'bucket',bucket,'key',object_key) FROM gcor.governance_outbox WHERE published_at IS NOT NULL UNION ALL SELECT json_build_object('source','buzz_event_imeta','id',encode(id,'hex'),'bucket','buzz-media','tags',tags) FROM public.events WHERE deleted_at IS NULL AND EXISTS (SELECT 1 FROM jsonb_array_elements(tags) tag WHERE jsonb_typeof(tag)='array' AND tag->>0='imeta')"
        Invoke-Checked {& docker compose @composeArgs exec -T postgres sh -c "psql -U '$pgUser' -d '$pgDb' -Atc `"$referenceSql`" > /tmp/gbuzz-object-references.jsonl"} 'PostgreSQL reference export failed.';Invoke-Checked {& docker compose @composeArgs cp postgres:/tmp/gbuzz-object-references.jsonl (Join-Path $content 'object-references.jsonl')} 'PostgreSQL reference copy failed.';& docker compose @composeArgs exec -T postgres rm -f /tmp/gbuzz-backup.dump /tmp/gbuzz-postgres-globals.sql /tmp/gbuzz-object-references.jsonl *> $null;Add-Checkpoint 'postgres' $mark 'custom dump, roles, and object references'
        $mark=[DateTimeOffset]::UtcNow;$oldAccess=$env:AWS_ACCESS_KEY_ID;$oldSecret=$env:AWS_SECRET_ACCESS_KEY;$oldEndpoint=$env:S3_ENDPOINT;$oldOutput=$env:BACKUP_OUTPUT
        try{$env:AWS_ACCESS_KEY_ID=$config.services.minio.environment.MINIO_ROOT_USER;$env:AWS_SECRET_ACCESS_KEY=$config.services.minio.environment.MINIO_ROOT_PASSWORD;$env:S3_ENDPOINT='http://minio:9000';$env:BACKUP_OUTPUT='/backup/minio';Invoke-Checked {& docker compose @composeArgs run --rm --no-deps -T -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e S3_ENDPOINT -e BACKUP_OUTPUT --volume "${content}:/backup" --volume "${PSScriptRoot}:/backup-tools:ro" --entrypoint python gcor-proxy /backup-tools/backup-minio-versions.py} 'MinIO version export failed.'}finally{$env:AWS_ACCESS_KEY_ID=$oldAccess;$env:AWS_SECRET_ACCESS_KEY=$oldSecret;$env:S3_ENDPOINT=$oldEndpoint;$env:BACKUP_OUTPUT=$oldOutput};Add-Checkpoint 'minio' $mark 'all buckets, versions, and delete markers'
        $mark=[DateTimeOffset]::UtcNow;Invoke-Checked {& docker compose @composeArgs run --rm --no-deps -T --volume "${content}:/backup" --volume "${PSScriptRoot}:/backup-tools:ro" --entrypoint python gcor-proxy /backup-tools/check-minio-references.py /backup/object-references.jsonl /backup/minio/inventory.json /backup/reference-check.json} 'Database-referenced MinIO object gate failed.';Add-Checkpoint 'referential-gate' $mark 'all database references resolved in exported current versions'
        $mark=[DateTimeOffset]::UtcNow;$before=& docker compose @composeArgs exec -T relay sh -c "find /data/git -type f -printf '%P|%s|%T@\n' | sort | sha256sum";if($LASTEXITCODE-ne 0){throw 'Unable to inventory relay Git data.'};Invoke-Checked {& docker compose @composeArgs exec -T relay tar -C /data/git -cf /tmp/relay-git.tar .} 'Relay Git archive failed.';Invoke-Checked {& docker compose @composeArgs cp relay:/tmp/relay-git.tar (Join-Path $content 'relay-git.tar')} 'Relay Git archive copy failed.';& docker compose @composeArgs exec -T relay rm -f /tmp/relay-git.tar *> $null;$after=& docker compose @composeArgs exec -T relay sh -c "find /data/git -type f -printf '%P|%s|%T@\n' | sort | sha256sum";if($LASTEXITCODE-ne 0-or$before-ne$after){throw 'Relay Git data changed during capture; retry the backup.'};Add-Checkpoint 'relay-git' $mark 'archive accepted after stable before/after inventory'
        $mark=[DateTimeOffset]::UtcNow;$cfg=Join-Path $content 'configuration';New-Item -ItemType Directory $cfg|Out-Null;foreach($path in @($plan.Files)+(Join-Path $RepoRoot '.env')){if(Test-Path $path){$relative=Get-GbuzzRelativePath $RepoRoot $path;$destination=Join-Path $cfg $relative;New-Item -ItemType Directory -Force (Split-Path -Parent $destination)|Out-Null;Copy-Item -LiteralPath $path -Destination $destination}};Copy-Item -Recurse -LiteralPath (Join-Path $RepoRoot 'migrations'),(Join-Path $RepoRoot 'observability') -Destination $cfg;Copy-Item -LiteralPath $ConfigPath -Destination (Join-Path $cfg 'windows-startup.compose-files.json');Add-Checkpoint 'configuration' $mark 'reviewed Compose plan, environment, migrations, and observability'
        $files=Get-ChildItem $content -Recurse -File|ForEach-Object{[ordered]@{path=(Get-GbuzzRelativePath $content $_.FullName).Replace('\','/');size=$_.Length;sha256=Get-FileSha256 $_.FullName}}
        $inner=[ordered]@{format=2;run_id=$runId;capture_started_at=$started.ToString('o');capture_finished_at=[DateTimeOffset]::UtcNow.ToString('o');consistency='component-consistent; components were captured sequentially, not atomically';source_stack='gbuzz';git_revision=(git rev-parse HEAD);compose_files=$plan.Files;checkpoints=$checkpoints;files=$files}
        $inner|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $content 'recovery-manifest.json') -Encoding utf8;$tar=Join-Path $work 'payload.tar';tar -C $content -cf $tar .;if($LASTEXITCODE-ne 0){throw 'Backup archive creation failed.'}
        Invoke-Checked {& docker compose @composeArgs run --rm --no-deps -T --volume "${work}:/backup" --volume "${PSScriptRoot}:/backup-tools:ro" --entrypoint python gcor-proxy /backup-tools/backup-evidence.py /backup/payload.tar} 'Inner evidence verification failed.'
        & (Join-Path $PSScriptRoot 'prune-backups.ps1') -BackupRoot $BackupRoot -MaxLocalBytes $MaxLocalBytes -ReserveBytes ((Get-Item $tar).Length+1MB) -ExcludePath $work|Out-Null
        $encrypted=Join-Path $work 'payload.gbuzzenc';$tag=Protect-BackupFile $tar $encrypted $key;$outerUnsigned=[ordered]@{format=1;run_id=$runId;created_at=$started.ToString('o');cipher='AES-256-CBC-HMAC-SHA256';artifact='payload.gbuzzenc';artifact_size=(Get-Item $encrypted).Length;artifact_sha256=Get-FileSha256 $encrypted;artifact_hmac_sha256=$tag};$canonical=$outerUnsigned|ConvertTo-Json -Compress;$outer=[ordered]@{};$outerUnsigned.Keys|ForEach-Object{$outer[$_]=$outerUnsigned[$_]};$outer['manifest_hmac_sha256']=Get-ManifestMac $canonical $key;$outer|ConvertTo-Json|Set-Content -LiteralPath (Join-Path $work 'manifest.json') -Encoding utf8
        Remove-Item -LiteralPath $content,$tar -Recurse -Force;New-Item -ItemType File (Join-Path $work 'COMPLETE')|Out-Null;Move-Item -LiteralPath $work -Destination $final;& (Join-Path $PSScriptRoot 'verify-backup.ps1') -BackupPath $final -Key $key -RepoRoot $RepoRoot -ConfigPath $ConfigPath
        $finished=[DateTimeOffset]::UtcNow;Write-Metrics $true $finished.ToUnixTimeSeconds() ([math]::Round(($finished-$started).TotalSeconds,3));Write-Output $final
    }finally{Pop-Location}
}catch{try{Write-Metrics $false 0 ([math]::Round(([DateTimeOffset]::UtcNow-$started).TotalSeconds,3))}catch{};Remove-Item -LiteralPath $work -Recurse -Force -ErrorAction SilentlyContinue;throw}
finally{try{if($cleanupContainers){Push-Location $RepoRoot;try{& docker compose @composeArgs exec -T postgres rm -f /tmp/gbuzz-backup.dump /tmp/gbuzz-postgres-globals.sql /tmp/gbuzz-object-references.jsonl *> $null;& docker compose @composeArgs exec -T relay rm -f /tmp/relay-git.tar *> $null}finally{Pop-Location}}}catch{}finally{$mutex.ReleaseMutex();$mutex.Dispose()}}
