[CmdletBinding(SupportsShouldProcess)]
param([ValidateSet('Audit','Apply','Rollback')][string]$Mode='Audit',[Parameter(Mandatory)][string]$BindAddress,[Parameter(Mandatory)][string]$RemoteCidr,[int]$Port=3000,[string]$RuleName='Gbuzz Relay - approved LAN only',[string]$AuditPath='C:\ProgramData\Gbuzz\security-audit\lan-boundary.json',[switch]$OwnerApprovedCidr,[string]$ExpectedRollbackSnapshot,[string]$EffectivePathEvidence,[string]$RoutedClientEvidence,[string]$ExposureEvidencePolicy)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;Import-Module (Join-Path $PSScriptRoot LanSecurity.psm1) -Force;Assert-GbuzzLanBoundary $BindAddress $RemoteCidr;if($Mode-eq'Apply'-and-not$OwnerApprovedCidr){throw 'Apply requires -OwnerApprovedCidr for the exact narrow CIDR.'}
function Values($value){@($value|ForEach-Object{([string]$_).Split(',')}|ForEach-Object{$_.Trim()}|Where-Object{$_})}
function Port-Overlaps($value,[int]$wanted){foreach($v in (Values $value)){if($v-eq'Any'){return $true};if($v-match'^(\d+)-(\d+)$'-and$wanted-ge[int]$Matches[1]-and$wanted-le[int]$Matches[2]){return $true};if($v-eq[string]$wanted){return $true}};$false}
function Address-Overlaps($value,[string]$wanted){foreach($v in (Values $value)){if($v-in@('Any','*','0.0.0.0/0','::/0','LocalSubnet','LocalSubnet4','LocalSubnet6')){return $true};if($v-eq$wanted){return $true};if($v-match'/' -and $wanted-notmatch':' ){try{if(Test-GbuzzAddressInAnyCidr $wanted $v){return $true}}catch{}};if($v-match'^([^\-]+)-([^\-]+)$'){try{if(Test-GbuzzAddressInRange $wanted $Matches[1] $Matches[2]){return $true}}catch{}}};$false}
function Get-Managed(){@(Get-NetFirewallRule -PolicyStore ActiveStore -ErrorAction SilentlyContinue|Where-Object DisplayName -eq $RuleName)}
function Rule-Compliant($r){$rules=@($r);if(-not$rules-or$rules.Count-ne1){return $false};$r=$rules[0];$p=$r|Get-NetFirewallPortFilter;$a=$r|Get-NetFirewallAddressFilter;$profiles=@(Values $r.Profile);$localPorts=@(Values $p.LocalPort);$localAddresses=@(Values $a.LocalAddress);$remoteAddresses=@(Values $a.RemoteAddress);$r.Enabled-eq'True'-and$r.Direction-eq'Inbound'-and$r.Action-eq'Allow'-and$p.Protocol-eq'TCP'-and$localPorts.Count-eq1-and$localPorts[0]-eq[string]$Port-and$localAddresses.Count-eq1-and$localAddresses[0]-eq$BindAddress-and$remoteAddresses.Count-eq1-and$remoteAddresses[0]-eq$RemoteCidr-and$profiles.Count-eq1-and$profiles[0]-eq'Private'}
function Snapshot($r){@($r|ForEach-Object{$p=$_|Get-NetFirewallPortFilter;$a=$_|Get-NetFirewallAddressFilter;[ordered]@{display_name=[string]$_.DisplayName;description=[string]$_.Description;direction=[string]$_.Direction;action=[string]$_.Action;enabled=[string]$_.Enabled;profile=@(Values $_.Profile|Sort-Object);protocol=[string]$p.Protocol;local_port=@(Values $p.LocalPort|Sort-Object);remote_port=@(Values $p.RemotePort|Sort-Object);local_address=@(Values $a.LocalAddress|Sort-Object);remote_address=@(Values $a.RemoteAddress|Sort-Object)}}|Sort-Object {($_|ConvertTo-Json -Depth 5 -Compress)})}
function Assert-Snapshot($expected,$actual,[string]$context){$a=@($expected)|ConvertTo-Json -Depth 7 -Compress;$b=@($actual)|ConvertTo-Json -Depth 7 -Compress;if($a-cne$b){throw "CRITICAL: firewall $context verification failed."}}
function Restore($s){if(-not$s){return};New-NetFirewallRule -DisplayName $s.display_name -Description $s.description -Direction $s.direction -Action $s.action -Enabled $s.enabled -Profile $s.profile -Protocol $s.protocol -LocalPort $s.local_port -RemotePort $s.remote_port -LocalAddress $s.local_address -RemoteAddress $s.remote_address|Out-Null}
function Protected([string]$path,[string]$root){$item=Get-Item -LiteralPath $path -Force -ErrorAction Stop;$full=$item.FullName;$approved=[IO.Path]::GetFullPath($root).TrimEnd('\')+'\';if(-not($full+'\').StartsWith($approved,[StringComparison]::OrdinalIgnoreCase)){throw 'Exposure evidence policy/key is outside approved protected root.'};$cursor=$item;while($cursor){if($cursor.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Exposure evidence policy/key traverses a reparse point.'};if($cursor.FullName.TrimEnd('\')-ieq$approved.TrimEnd('\')){break};$cursor=if($cursor-is[IO.DirectoryInfo]){$cursor.Parent}else{$cursor.Directory}};$acl=Get-Acl -LiteralPath $full;if(-not$acl.AreAccessRulesProtected){throw 'Exposure evidence policy/key ACL inherits.'};$bad=@($acl.Access|Where-Object{$_.AccessControlType-eq'Allow'-and$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value-notin@('S-1-5-18','S-1-5-32-544')});if($bad){throw 'Exposure evidence policy/key has unapproved write authority.'};$full}
function ProofPayload($p){[ordered]@{schema_version=$p.schema_version;evidence_type=$p.evidence_type;evidence_mode=$p.evidence_mode;probe_role=$p.probe_role;key_id=$p.key_id;probe_identity=$p.probe_identity;probe_host=$p.probe_host;observed_source_address=$p.observed_source_address;relay_address=$p.relay_address;port=$p.port;approved_cidr=$p.approved_cidr;expected_reachable=$p.expected_reachable;actual_reachable=$p.actual_reachable;passed=$p.passed;protocol=$p.protocol;deployment_id=$p.deployment_id;release_id=$p.release_id;compose_digest=$p.compose_digest;firewall_policy_digest=$p.firewall_policy_digest;run_id=$p.run_id;nonce=$p.nonce;started_at=$p.started_at;ended_at=$p.ended_at;tool=$p.tool;tool_version=$p.tool_version;error=$p.error}|ConvertTo-Json -Compress}
function Verify-Proof($p,$key){if($key.algorithm-cne'RS256'-or[int]$key.bits-lt3072-or$key.revoked){throw 'Probe signing key is weak, unsupported, or revoked.'};try{$rsa=[Security.Cryptography.RSA]::Create();$rp=[Security.Cryptography.RSAParameters]::new();$rp.Modulus=[Convert]::FromBase64String([string]$key.modulus_b64);$rp.Exponent=[Convert]::FromBase64String([string]$key.exponent_b64);$rsa.ImportParameters($rp);$data=[Text.Encoding]::UTF8.GetBytes((ProofPayload $p));$sig=[Convert]::FromBase64String([string]$p.signature_b64);if($rsa.KeySize-lt3072-or-not$rsa.VerifyData($data,$sig,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)){throw 'invalid'}}catch{throw 'Reachability proof signature is invalid.'}}
function Validate-Proofs(){if(-not$ExposureEvidencePolicy-or-not$EffectivePathEvidence-or-not$RoutedClientEvidence){return $false};try{$cfg=Get-Content -LiteralPath $ExposureEvidencePolicy -Raw|ConvertFrom-Json -ErrorAction Stop;if($cfg.schema_version-ne2-or-not$cfg.approved_root-or-not$cfg.deployment_id-or-not$cfg.release_id-or$cfg.compose_digest-notmatch'^[0-9a-f]{64}$'-or$cfg.firewall_policy_digest-notmatch'^[0-9a-f]{64}$'-or-not$cfg.run_id-or-not$cfg.nonce-or[int]$cfg.max_age_minutes-lt1-or@($cfg.probe_keys).Count-ne2){throw 'Exposure evidence policy is incomplete.'};[void](Protected $ExposureEvidencePolicy $cfg.approved_root);$proofs=@($EffectivePathEvidence,$RoutedClientEvidence|ForEach-Object{Get-Content -LiteralPath $_ -Raw|ConvertFrom-Json -ErrorAction Stop});if($proofs.Count-ne2){throw 'Exactly two reachability proofs are required.'};foreach($p in $proofs){$key=@($cfg.probe_keys|Where-Object{$_.key_id-ceq$p.key_id-and$_.probe_role-ceq$p.probe_role});if($key.Count-ne1){throw 'Probe key/role is not independently approved.'};if($p.schema_version-ne1-or$p.evidence_type-cne'gbuzz-lan-reachability'-or$p.evidence_mode-cne'activation_probe'-or$p.probe_role-notin@('allowed_client','excluded_client')-or$p.passed-ne$true-or$p.deployment_id-cne$cfg.deployment_id-or$p.release_id-cne$cfg.release_id-or$p.compose_digest-cne$cfg.compose_digest-or$p.firewall_policy_digest-cne$cfg.firewall_policy_digest-or$p.run_id-cne$cfg.run_id-or$p.nonce-cne$cfg.nonce-or$p.relay_address-cne$BindAddress-or[int]$p.port-ne$Port-or$p.approved_cidr-cne$RemoteCidr-or$p.protocol-cne'tcp'-or-not$p.probe_identity-or-not$p.probe_host-or$p.probe_host-ceq$cfg.gbuzz_host_identity-or-not$p.observed_source_address-or-not$p.tool-or-not$p.tool_version){throw 'Reachability proof schema or deployment binding failed.'};$start=[DateTimeOffset]$p.started_at;$end=[DateTimeOffset]$p.ended_at;$age=[DateTimeOffset]::UtcNow-$end;if($end-lt$start-or$age.TotalMinutes-lt0-or$age.TotalMinutes-gt[int]$cfg.max_age_minutes){throw 'Reachability proof is stale, future-dated, or has an invalid interval.'};Verify-Proof $p $key[0]};$allowed=@($proofs|Where-Object{$_.probe_role-ceq'allowed_client'-and$_.expected_reachable-eq$true-and$_.actual_reachable-eq$true});$denied=@($proofs|Where-Object{$_.probe_role-ceq'excluded_client'-and$_.expected_reachable-eq$false-and$_.actual_reachable-eq$false});if($allowed.Count-ne1-or$denied.Count-ne1-or$allowed[0].key_id-ceq$denied[0].key_id-or$allowed[0].probe_identity-ceq$denied[0].probe_identity-or$allowed[0].probe_host-ceq$denied[0].probe_host-or-not(Test-GbuzzAddressInAnyCidr $allowed[0].observed_source_address $RemoteCidr)-or(Test-GbuzzAddressInAnyCidr $denied[0].observed_source_address $RemoteCidr)){throw 'Distinct correctly located allowed and excluded probe results are required.'};return $true}catch{if($Mode-eq'Apply'){throw};return $false}}

$candidateRules=@(Get-NetFirewallRule -PolicyStore ActiveStore -ErrorAction Stop|Where-Object{$_.Enabled-eq'True'-and$_.Direction-eq'Inbound'-and$_.Action-eq'Allow'-and$_.DisplayName-ne$RuleName}|ForEach-Object{$r=$_;$p=$_|Get-NetFirewallPortFilter;$a=$_|Get-NetFirewallAddressFilter;if(($p.Protocol-in@('TCP','Any',256))-and(Port-Overlaps $p.LocalPort $Port)-and(Address-Overlaps $a.LocalAddress $BindAddress)){[ordered]@{name=$r.DisplayName;policy_store_source_type=[string]$r.PolicyStoreSourceType;protocol=[string]$p.Protocol;local_port=@(Values $p.LocalPort);local_address=@(Values $a.LocalAddress);remote_address=@(Values $a.RemoteAddress);profiles=@(Values $r.Profile)}}})
$nat=@();if(Get-Command Get-NetNatStaticMapping -ErrorAction SilentlyContinue){$nat=@(Get-NetNatStaticMapping -ErrorAction SilentlyContinue|Where-Object{$_.ExternalPort-eq$Port-or$_.InternalPort-eq$Port})}
$portproxy=@();try{$portproxy=@(netsh interface portproxy show all|Select-String -Pattern "(^|\s)$Port(\s|$)")}catch{$portproxy=@('inventory-unavailable')}
$forwarders=@();foreach($name in @('com.docker.backend','wslrelay','wslhost')){if(Get-Process -Name $name -ErrorAction SilentlyContinue){$forwarders+=$name}}
$managed=Get-Managed;$ok=Rule-Compliant $managed;$exposureLimits=@();if($nat.Count){$exposureLimits+='Windows NAT mapping overlaps relay port'};if($portproxy.Count){$exposureLimits+='portproxy mapping overlaps relay port or inventory unavailable'};if($forwarders.Count){$exposureLimits+='Docker/WSL forwarding requires separate effective-path verification'}
$proofOk=Validate-Proofs
if($Mode-eq'Audit'){[ordered]@{bind=$BindAddress;cidr=$RemoteCidr;port=$Port;managed_rule_compliant=$ok;overlapping_allow_rules=$candidateRules;nat_mappings=$nat.Count;portproxy_findings=$portproxy.Count;forwarding_components=$forwarders;limitations=$exposureLimits;effective_path_and_routed_client_proof=$proofOk;compliant=$ok-and-not$candidateRules.Count-and-not$nat.Count-and-not$portproxy.Count-and$proofOk}|ConvertTo-Json -Depth 7;return}
if($Mode-eq'Rollback'){if(-not$ExpectedRollbackSnapshot){throw 'Explicit rollback requires -ExpectedRollbackSnapshot.'};$expected=@(Get-Content -LiteralPath $ExpectedRollbackSnapshot -Raw|ConvertFrom-Json);if($managed-and$PSCmdlet.ShouldProcess($RuleName,'Remove managed rule')){$managed|Remove-NetFirewallRule};foreach($s in $expected){if($PSCmdlet.ShouldProcess($RuleName,'Restore prior managed rule')){Restore $s}};Assert-Snapshot $expected (Snapshot (Get-Managed)) 'explicit rollback';return}
if(-not$proofOk){throw 'Apply requires authenticated allowed and excluded routed-client proofs.'}
if($managed.Count-gt1){throw 'Multiple managed firewall rules found.'};if($candidateRules){throw "Overlapping inbound allows must be narrowed: $($candidateRules.name-join', ')"};if($nat.Count-or$portproxy.Count){throw 'NAT or portproxy exposure overlaps the relay port.'}
$prior=Snapshot $managed
try{if($managed-and$PSCmdlet.ShouldProcess($RuleName,'Replace managed rule')){$managed|Remove-NetFirewallRule};if($PSCmdlet.ShouldProcess($RuleName,'Create LAN-only rule')){New-NetFirewallRule -DisplayName $RuleName -Direction Inbound -Action Allow -Protocol TCP -LocalPort $Port -LocalAddress $BindAddress -RemoteAddress $RemoteCidr -Profile Private|Out-Null};if(-not(Rule-Compliant (Get-Managed))){throw 'Post-write firewall verification failed.'}}
catch{$cause=$_.Exception.Message;Get-Managed|Remove-NetFirewallRule -ErrorAction SilentlyContinue;foreach($s in $prior){Restore $s};Assert-Snapshot $prior (Snapshot (Get-Managed)) 'rollback';throw "Firewall transaction rolled back and verified. Cause: $cause"}
$dir=Split-Path $AuditPath;if($PSCmdlet.ShouldProcess($dir,'Create audit directory')){New-Item -ItemType Directory -Force $dir|Out-Null};if($PSCmdlet.ShouldProcess($AuditPath,'Write evidence')){[ordered]@{applied_at=[DateTimeOffset]::UtcNow.ToString('o');bind=$BindAddress;cidr=$RemoteCidr;port=$Port;overlap_count=0;forwarding_components=$forwarders;exposure_proof='Windows firewall rule only; routed-client negative probe still required'}|ConvertTo-Json|Set-Content -LiteralPath $AuditPath -Encoding utf8}
