[CmdletBinding(SupportsShouldProcess)]
param([ValidateSet('Audit','Apply','Rollback')][string]$Mode='Audit',[Parameter(Mandatory)][string]$BindAddress,[Parameter(Mandatory)][string]$RemoteCidr,[int]$Port=3000,[string]$RuleName='Gbuzz Relay - approved LAN only',[string]$AuditPath='C:\ProgramData\Gbuzz\security-audit\lan-boundary.json',[switch]$OwnerApprovedCidr)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;Import-Module (Join-Path $PSScriptRoot LanSecurity.psm1) -Force;Assert-GbuzzLanBoundary $BindAddress $RemoteCidr;if($Mode-eq'Apply'-and-not$OwnerApprovedCidr){throw 'Apply requires -OwnerApprovedCidr for the exact narrow CIDR.'}
function Values($value){@($value|ForEach-Object{([string]$_).Split(',')}|ForEach-Object{$_.Trim()}|Where-Object{$_})}
function Port-Overlaps($value,[int]$wanted){foreach($v in (Values $value)){if($v-eq'Any'){return $true};if($v-match'^(\d+)-(\d+)$'-and$wanted-ge[int]$Matches[1]-and$wanted-le[int]$Matches[2]){return $true};if($v-eq[string]$wanted){return $true}};$false}
function Address-Overlaps($value,[string]$wanted){foreach($v in (Values $value)){if($v-in@('Any','*','0.0.0.0/0','::/0','LocalSubnet','LocalSubnet4','LocalSubnet6')){return $true};if($v-eq$wanted){return $true};if($v-match'/' -and $wanted-notmatch':' ){try{if(Test-GbuzzAddressInAnyCidr $wanted $v){return $true}}catch{}};if($v-match'^([^\-]+)-([^\-]+)$'){try{if(Test-GbuzzAddressInRange $wanted $Matches[1] $Matches[2]){return $true}}catch{}}};$false}
function Get-Managed(){@(Get-NetFirewallRule -PolicyStore ActiveStore -ErrorAction SilentlyContinue|Where-Object DisplayName -eq $RuleName)}
function Rule-Compliant($r){if(-not$r-or$r.Count-ne1){return $false};$p=$r|Get-NetFirewallPortFilter;$a=$r|Get-NetFirewallAddressFilter;$profiles=Values $r.Profile;$r.Enabled-eq'True'-and$r.Direction-eq'Inbound'-and$r.Action-eq'Allow'-and$p.Protocol-eq'TCP'-and(Values $p.LocalPort).Count-eq1-and$p.LocalPort-eq[string]$Port-and(Values $a.LocalAddress).Count-eq1-and$a.LocalAddress-eq$BindAddress-and(Values $a.RemoteAddress).Count-eq1-and$a.RemoteAddress-eq$RemoteCidr-and$profiles.Count-eq1-and$profiles[0]-eq'Private'}
function Snapshot($r){if(-not$r){return $null};$p=$r|Get-NetFirewallPortFilter;$a=$r|Get-NetFirewallAddressFilter;[ordered]@{display_name=$r.DisplayName;description=$r.Description;direction=[string]$r.Direction;action=[string]$r.Action;enabled=[string]$r.Enabled;profile=[string]$r.Profile;protocol=[string]$p.Protocol;local_port=[string]$p.LocalPort;remote_port=[string]$p.RemotePort;local_address=@($a.LocalAddress);remote_address=@($a.RemoteAddress)}}
function Restore($s){if(-not$s){return};New-NetFirewallRule -DisplayName $s.display_name -Description $s.description -Direction $s.direction -Action $s.action -Enabled $s.enabled -Profile $s.profile -Protocol $s.protocol -LocalPort $s.local_port -RemotePort $s.remote_port -LocalAddress $s.local_address -RemoteAddress $s.remote_address|Out-Null}

$candidateRules=@(Get-NetFirewallRule -PolicyStore ActiveStore -ErrorAction Stop|Where-Object{$_.Enabled-eq'True'-and$_.Direction-eq'Inbound'-and$_.Action-eq'Allow'-and$_.DisplayName-ne$RuleName}|ForEach-Object{$r=$_;$p=$_|Get-NetFirewallPortFilter;$a=$_|Get-NetFirewallAddressFilter;if(($p.Protocol-in@('TCP','Any',256))-and(Port-Overlaps $p.LocalPort $Port)-and(Address-Overlaps $a.LocalAddress $BindAddress)){[ordered]@{name=$r.DisplayName;policy_store_source_type=[string]$r.PolicyStoreSourceType;protocol=[string]$p.Protocol;local_port=@(Values $p.LocalPort);local_address=@(Values $a.LocalAddress);remote_address=@(Values $a.RemoteAddress);profiles=@(Values $r.Profile)}}})
$nat=@();if(Get-Command Get-NetNatStaticMapping -ErrorAction SilentlyContinue){$nat=@(Get-NetNatStaticMapping -ErrorAction SilentlyContinue|Where-Object{$_.ExternalPort-eq$Port-or$_.InternalPort-eq$Port})}
$portproxy=@();try{$portproxy=@(netsh interface portproxy show all|Select-String -Pattern "(^|\s)$Port(\s|$)")}catch{$portproxy=@('inventory-unavailable')}
$forwarders=@();foreach($name in @('com.docker.backend','wslrelay','wslhost')){if(Get-Process -Name $name -ErrorAction SilentlyContinue){$forwarders+=$name}}
$managed=Get-Managed;$ok=Rule-Compliant $managed;$exposureLimits=@();if($nat.Count){$exposureLimits+='Windows NAT mapping overlaps relay port'};if($portproxy.Count){$exposureLimits+='portproxy mapping overlaps relay port or inventory unavailable'};if($forwarders.Count){$exposureLimits+='Docker/WSL forwarding requires separate effective-path verification'}
if($Mode-eq'Audit'){[ordered]@{bind=$BindAddress;cidr=$RemoteCidr;port=$Port;managed_rule_compliant=$ok;overlapping_allow_rules=$candidateRules;nat_mappings=$nat.Count;portproxy_findings=$portproxy.Count;forwarding_components=$forwarders;limitations=$exposureLimits;compliant=$ok-and-not$candidateRules.Count-and-not$nat.Count-and-not$portproxy.Count}|ConvertTo-Json -Depth 7;return}
if($Mode-eq'Rollback'){if($managed-and$PSCmdlet.ShouldProcess($RuleName,'Remove managed rule')){$managed|Remove-NetFirewallRule};return}
if($managed.Count-gt1){throw 'Multiple managed firewall rules found.'};if($candidateRules){throw "Overlapping inbound allows must be narrowed: $($candidateRules.name-join', ')"};if($nat.Count-or$portproxy.Count){throw 'NAT or portproxy exposure overlaps the relay port.'}
$prior=if($managed.Count){Snapshot $managed[0]}else{$null}
try{if($managed-and$PSCmdlet.ShouldProcess($RuleName,'Replace managed rule')){$managed|Remove-NetFirewallRule};if($PSCmdlet.ShouldProcess($RuleName,'Create LAN-only rule')){New-NetFirewallRule -DisplayName $RuleName -Direction Inbound -Action Allow -Protocol TCP -LocalPort $Port -LocalAddress $BindAddress -RemoteAddress $RemoteCidr -Profile Private|Out-Null};if(-not(Rule-Compliant (Get-Managed))){throw 'Post-write firewall verification failed.'}}
catch{$cause=$_.Exception.Message;Get-Managed|Remove-NetFirewallRule -ErrorAction SilentlyContinue;Restore $prior;$restored=Get-Managed;if(($prior-and-not$restored.Count)-or(-not$prior-and$restored.Count)){throw "CRITICAL: firewall rollback verification failed. Cause: $cause"};throw "Firewall transaction rolled back and verified. Cause: $cause"}
$dir=Split-Path $AuditPath;if($PSCmdlet.ShouldProcess($dir,'Create audit directory')){New-Item -ItemType Directory -Force $dir|Out-Null};if($PSCmdlet.ShouldProcess($AuditPath,'Write evidence')){[ordered]@{applied_at=[DateTimeOffset]::UtcNow.ToString('o');bind=$BindAddress;cidr=$RemoteCidr;port=$Port;overlap_count=0;forwarding_components=$forwarders;exposure_proof='Windows firewall rule only; routed-client negative probe still required'}|ConvertTo-Json|Set-Content -LiteralPath $AuditPath -Encoding utf8}
