Set-StrictMode -Version Latest
function ConvertTo-IPv4UInt32([string]$Address){$p=[Net.IPAddress]::Parse($Address);if($p.AddressFamily-ne[Net.Sockets.AddressFamily]::InterNetwork){throw "IPv4 required: $Address"};$b=$p.GetAddressBytes();[array]::Reverse($b);[BitConverter]::ToUInt32($b,0)}
function Get-Mask([int]$Bits){[uint32]([math]::Pow(2,32)-[math]::Pow(2,32-$Bits))}
function Test-GbuzzPrivateIPv4([string]$Address){try{$v=ConvertTo-IPv4UInt32 $Address}catch{return $false};foreach($r in @(@('10.0.0.0',8),@('172.16.0.0',12),@('192.168.0.0',16))){$n=[int]$r[1];$m=Get-Mask $n;if(($v-band$m)-eq((ConvertTo-IPv4UInt32 $r[0])-band$m)){return $true}};$false}
function Test-GbuzzAddressInCidr([string]$Address,[string]$Cidr){$p=$Cidr.Split('/');if($p.Count-ne2){throw "Invalid CIDR: $Cidr"};$n=0;if(-not[int]::TryParse($p[1],[ref]$n)-or$n-lt24-or$n-gt32){throw "Owner-approved LAN prefix must be /24 through /32: $Cidr"};if(-not(Test-GbuzzPrivateIPv4 $p[0])){throw "LAN CIDR must be RFC1918: $Cidr"};$m=Get-Mask $n;((ConvertTo-IPv4UInt32 $Address)-band$m)-eq((ConvertTo-IPv4UInt32 $p[0])-band$m)}
function Test-GbuzzAddressInAnyCidr([string]$Address,[string]$Cidr){$p=$Cidr.Split('/');$n=0;if($p.Count-ne2-or-not[int]::TryParse($p[1],[ref]$n)-or$n-lt0-or$n-gt32){throw "Invalid CIDR: $Cidr"};$m=Get-Mask $n;((ConvertTo-IPv4UInt32 $Address)-band$m)-eq((ConvertTo-IPv4UInt32 $p[0])-band$m)}
function Test-GbuzzAddressInRange([string]$Address,[string]$First,[string]$Last){$v=ConvertTo-IPv4UInt32 $Address;$v-ge(ConvertTo-IPv4UInt32 $First)-and$v-le(ConvertTo-IPv4UInt32 $Last)}
function Assert-GbuzzLanBoundary([string]$BindAddress,[string]$RemoteCidr){if(-not(Test-GbuzzPrivateIPv4 $BindAddress)){throw 'Bind address must be explicit RFC1918 IPv4.'};if(-not(Test-GbuzzAddressInCidr $BindAddress $RemoteCidr)){throw 'Bind address is outside approved LAN CIDR.'};if($BindAddress-notin@(Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop|% IPAddress)){throw "Address is not assigned to this host: $BindAddress"}}
Export-ModuleMember -Function ConvertTo-IPv4UInt32,Test-GbuzzPrivateIPv4,Test-GbuzzAddressInCidr,Test-GbuzzAddressInAnyCidr,Test-GbuzzAddressInRange,Assert-GbuzzLanBoundary
