[CmdletBinding(SupportsShouldProcess)]
param([ValidateSet('Audit','Apply','Rollback')][string]$Mode='Audit',[Parameter(Mandatory)][string]$OperatingIdentity,[string[]]$SecretPaths=@('.env','C:\ProgramData\Gbuzz\secrets'),[string]$EvidenceRoot='C:\ProgramData\Gbuzz\security-audit',[string]$RollbackManifest)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Sid([string]$i){([Security.Principal.NTAccount]::new($i)).Translate([Security.Principal.SecurityIdentifier]).Value}
function Target([string]$p){[IO.Path]::GetFullPath($(if([IO.Path]::IsPathRooted($p)){$p}else{Join-Path (Split-Path -Parent $PSScriptRoot) $p}))}
function Allowed($acl){@($acl.Access|? AccessControlType -eq Allow|%{$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value}|sort -Unique)}
function Write-Dacl($t,$a){if((Get-Item $t)-is[IO.DirectoryInfo]){[IO.Directory]::SetAccessControl($t,$a)}else{[IO.File]::SetAccessControl($t,$a)}}
function Restrict($t){$a=Get-Acl $t;$a.SetAccessRuleProtection($true,$false);foreach($r in @($a.Access)){$a.RemoveAccessRuleAll($r)};$inherit=if((Get-Item $t)-is[IO.DirectoryInfo]){[Security.AccessControl.InheritanceFlags]'ContainerInherit,ObjectInherit'}else{[Security.AccessControl.InheritanceFlags]::None};foreach($id in @($OperatingIdentity,'BUILTIN\Administrators','NT AUTHORITY\SYSTEM')){$a.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($id,'FullControl',$inherit,[Security.AccessControl.PropagationFlags]::None,'Allow'))};Write-Dacl $t $a}
$allow=@((Sid $OperatingIdentity),'S-1-5-32-544','S-1-5-18'|sort -Unique);$targets=@($SecretPaths|%{Target $_})
if($Mode-eq'Rollback'){if(-not$RollbackManifest-or-not(Test-Path $RollbackManifest)){throw 'Valid -RollbackManifest required.'};$m=Get-Content -Raw $RollbackManifest|ConvertFrom-Json;foreach($i in $m.paths){$t=Target $i.path;if($t-ne$i.path){throw 'Non-canonical rollback path.'};if($PSCmdlet.ShouldProcess($t,'Restore previous ACL')){$a=Get-Acl $t;$a.SetAccessRuleProtection([bool]$i.protected,$false);foreach($r in @($a.Access)){$a.RemoveAccessRuleAll($r)};foreach($r in $i.rules){$identity=[Security.Principal.SecurityIdentifier]::new([string]$r.sid);$a.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($identity,[Security.AccessControl.FileSystemRights]([int]$r.rights),[Security.AccessControl.InheritanceFlags]([int]$r.inheritance),[Security.AccessControl.PropagationFlags]([int]$r.propagation),[Security.AccessControl.AccessControlType]([int]$r.type)))};Write-Dacl $t $a}};return}
$report=@();foreach($t in $targets){if(-not(Test-Path $t)){throw "Secret path missing: $t"};$a=Get-Acl $t;$actual=Allowed $a;$denies=@($a.Access|? AccessControlType -eq Deny);$badRights=@($a.Access|?{$_.AccessControlType-eq'Allow'-and$_.FileSystemRights-ne'FullControl'});$duplicates=@($a.Access|? AccessControlType -eq Allow|group {$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value}|? Count -gt 1);$ok=$a.AreAccessRulesProtected-and-not@($actual|?{$_-notin$allow}).Count-and-not@($allow|?{$_-notin$actual}).Count-and-not$denies.Count-and-not$badRights.Count-and-not$duplicates.Count;$report+=[ordered]@{path=$t;protected=$a.AreAccessRulesProtected;allow_sids=$actual;deny_aces=$denies.Count;non_full_control_aces=$badRights.Count;overlapping_allow_identities=@($duplicates|% Name);compliant=$ok}}
if($Mode-eq'Audit'){$report|ConvertTo-Json -Depth 5;return}
$stamp=[DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssZ');if($PSCmdlet.ShouldProcess($EvidenceRoot,'Create protected audit directory')){New-Item -ItemType Directory -Force $EvidenceRoot|Out-Null;Restrict $EvidenceRoot};$m=[ordered]@{created_at=[DateTimeOffset]::UtcNow.ToString('o');operating_identity=$OperatingIdentity;paths=@()};foreach($t in $targets){$acl=Get-Acl $t;$rules=@($acl.Access|%{[ordered]@{sid=$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value;rights=[int]$_.FileSystemRights;inheritance=[int]$_.InheritanceFlags;propagation=[int]$_.PropagationFlags;type=[int]$_.AccessControlType}});$m.paths+=[ordered]@{path=$t;protected=$acl.AreAccessRulesProtected;rules=$rules}};$rollback=Join-Path $EvidenceRoot "secret-acl-rollback-$stamp.json";if($PSCmdlet.ShouldProcess($rollback,'Write rollback manifest')){$m|ConvertTo-Json -Depth 7|Set-Content $rollback -Encoding utf8}
try{foreach($t in $targets){if($PSCmdlet.ShouldProcess($t,'Replace secret ACL')){Restrict $t}}}catch{foreach($i in $m.paths){$t=$i.path;$a=Get-Acl $t;$a.SetAccessRuleProtection([bool]$i.protected,$false);foreach($r in @($a.Access)){$a.RemoveAccessRuleAll($r)};foreach($r in $i.rules){$identity=[Security.Principal.SecurityIdentifier]::new([string]$r.sid);$a.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($identity,[Security.AccessControl.FileSystemRights]([int]$r.rights),[Security.AccessControl.InheritanceFlags]([int]$r.inheritance),[Security.AccessControl.PropagationFlags]([int]$r.propagation),[Security.AccessControl.AccessControlType]([int]$r.type)))};Write-Dacl $t $a};throw "Secret ACL transaction rolled back: $($_.Exception.Message)"}
foreach($t in $targets){$a=Get-Acl $t;$actual=Allowed $a;$denies=@($a.Access|? AccessControlType -eq Deny);$bad=@($a.Access|?{$_.AccessControlType-eq'Allow'-and$_.FileSystemRights-ne'FullControl'});$dupes=@($a.Access|? AccessControlType -eq Allow|group {$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value}|? Count -gt 1);if(-not$a.AreAccessRulesProtected-or@($actual|?{$_-notin$allow}).Count-or@($allow|?{$_-notin$actual}).Count-or$denies.Count-or$bad.Count-or$dupes.Count){throw "Secret ACL verification failed closed: $t"}}
[ordered]@{applied_at=[DateTimeOffset]::UtcNow.ToString('o');paths=$targets;rollback_manifest=$rollback}|ConvertTo-Json
