[CmdletBinding(SupportsShouldProcess)]
param([ValidateSet('Audit','Apply','Rollback')][string]$Mode='Audit',[Parameter(Mandatory)][string]$OperatingIdentity,[string[]]$SecretPaths=@('.env','C:\ProgramData\Gbuzz\secrets'),[string]$EvidenceRoot='C:\ProgramData\Gbuzz\security-audit',[string]$RollbackManifest,[string]$ManifestMacKeyPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Sid([string]$i){([Security.Principal.NTAccount]::new($i)).Translate([Security.Principal.SecurityIdentifier]).Value}
function Target([string]$p){[IO.Path]::GetFullPath($(if([IO.Path]::IsPathRooted($p)){$p}else{Join-Path (Split-Path -Parent $PSScriptRoot) $p}))}
function Assert-SafeTarget([string]$p){$item=Get-Item -LiteralPath $p -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw "Reparse-point secret path rejected: $p"};if($item.FullName-ne(Target $p)){throw "Non-canonical secret path rejected: $p"};$item.FullName}
function Allowed($acl){@($acl.Access|Where-Object AccessControlType -eq Allow|ForEach-Object{$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value}|Sort-Object -Unique)}
function Write-Dacl($t,$a){if((Get-Item -LiteralPath $t)-is[IO.DirectoryInfo]){[IO.Directory]::SetAccessControl($t,$a)}else{[IO.File]::SetAccessControl($t,$a)}}
function Restore($entry){$a=Get-Acl -LiteralPath $entry.path;$a.SetSecurityDescriptorSddlForm([string]$entry.access_sddl,[Security.AccessControl.AccessControlSections]::Access);Write-Dacl $entry.path $a}
function Snapshot([string]$t){$a=Get-Acl -LiteralPath $t;[ordered]@{path=$t;protected=$a.AreAccessRulesProtected;access_sddl=$a.GetSecurityDescriptorSddlForm([Security.AccessControl.AccessControlSections]::Access);rules=@($a.Access|ForEach-Object{[ordered]@{sid=$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value;rights=[int]$_.FileSystemRights;inheritance=[int]$_.InheritanceFlags;propagation=[int]$_.PropagationFlags;type=[int]$_.AccessControlType}})}}
function Assert-Restored($entry){$current=(Get-Acl -LiteralPath $entry.path).GetSecurityDescriptorSddlForm([Security.AccessControl.AccessControlSections]::Access);if($current-ne$entry.access_sddl){throw "CRITICAL: ACL rollback verification failed: $($entry.path)"}}
function Test-Compliant([string]$t,$allowed){$a=Get-Acl -LiteralPath $t;$actual=Allowed $a;$denies=@($a.Access|Where-Object AccessControlType -eq Deny);$bad=@($a.Access|Where-Object{$_.AccessControlType-eq'Allow'-and$_.FileSystemRights-ne'FullControl'});$dupes=@($a.Access|Where-Object AccessControlType -eq Allow|Group-Object {$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value}|Where-Object Count -gt 1);$a.AreAccessRulesProtected-and-not@($actual|Where-Object{$_-notin$allowed}).Count-and-not@($allowed|Where-Object{$_-notin$actual}).Count-and-not$denies.Count-and-not$bad.Count-and-not$dupes.Count}
function Restrict([string]$t){$a=Get-Acl -LiteralPath $t;$a.SetAccessRuleProtection($true,$false);foreach($r in @($a.Access)){$a.RemoveAccessRuleAll($r)};$inherit=if((Get-Item -LiteralPath $t)-is[IO.DirectoryInfo]){[Security.AccessControl.InheritanceFlags]'ContainerInherit,ObjectInherit'}else{[Security.AccessControl.InheritanceFlags]::None};foreach($id in @($OperatingIdentity,'BUILTIN\Administrators','NT AUTHORITY\SYSTEM')){$a.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($id,'FullControl',$inherit,[Security.AccessControl.PropagationFlags]::None,'Allow'))};Write-Dacl $t $a}
function Read-MacKey(){if(-not$ManifestMacKeyPath-or-not(Test-Path -LiteralPath $ManifestMacKeyPath -PathType Leaf)){throw 'Protected -ManifestMacKeyPath is required.'};$item=Get-Item -LiteralPath $ManifestMacKeyPath -Force;if($item.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'Manifest MAC key cannot be a reparse point.'};$key=[IO.File]::ReadAllBytes($item.FullName);if($key.Length-lt32){throw 'Manifest MAC key must contain at least 32 bytes.'};$key}
function Mac([byte[]]$key,[string]$text){$h=New-Object Security.Cryptography.HMACSHA256 (,$key);try{(([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($text))))-replace'-','').ToLowerInvariant()}finally{$h.Dispose()}}
function ManifestPayload($m){[ordered]@{schema_version=$m.schema_version;operation=$m.operation;run_id=$m.run_id;host_id=$m.host_id;operating_identity=$m.operating_identity;target_set_digest=$m.target_set_digest;created_at=$m.created_at;paths=$m.paths}|ConvertTo-Json -Depth 9 -Compress}

$allow=@((Sid $OperatingIdentity),'S-1-5-32-544','S-1-5-18'|Sort-Object -Unique)
$targets=@($SecretPaths|ForEach-Object{Target $_}|Sort-Object -Unique);if($targets.Count-ne$SecretPaths.Count){throw 'Duplicate or aliased secret paths rejected.'}
foreach($t in $targets){if(-not(Test-Path -LiteralPath $t)){throw "Secret path missing: $t"};[void](Assert-SafeTarget $t)}
$sha=[Security.Cryptography.SHA256]::Create();try{$targetDigest=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes(($targets-join"`n"))))-replace'-','').ToLowerInvariant()}finally{$sha.Dispose()}

if($Mode-eq'Rollback'){
  $key=Read-MacKey;if(-not$RollbackManifest-or-not(Test-Path -LiteralPath $RollbackManifest -PathType Leaf)){throw 'Valid -RollbackManifest required.'};$m=Get-Content -LiteralPath $RollbackManifest -Raw|ConvertFrom-Json
  if($m.schema_version-ne2-or$m.operation-ne'restrict-secret-acls'-or$m.host_id-ne[Environment]::MachineName-or$m.operating_identity-ne$OperatingIdentity-or$m.target_set_digest-ne$targetDigest){throw 'Rollback manifest is for another host, operation, identity, or target set.'}
  $manifestTargets=@($m.paths|ForEach-Object{[string]$_.path}|Sort-Object -Unique);if($manifestTargets.Count-ne$targets.Count-or(Compare-Object $targets $manifestTargets)){throw 'Rollback target set mismatch.'}
  if((Mac $key (ManifestPayload $m))-ne[string]$m.mac_sha256){throw 'Rollback manifest MAC verification failed.'}
  foreach($entry in $m.paths){[void](Assert-SafeTarget $entry.path);if($PSCmdlet.ShouldProcess($entry.path,'Restore previous ACL')){Restore $entry;Assert-Restored $entry}};return
}

$report=@($targets|ForEach-Object{[ordered]@{path=$_;compliant=(Test-Compliant $_ $allow)}});if($Mode-eq'Audit'){$report|ConvertTo-Json -Depth 4;return}
$key=Read-MacKey;$snapshots=@($targets|ForEach-Object{Snapshot $_});$m=[ordered]@{schema_version=2;operation='restrict-secret-acls';run_id=[guid]::NewGuid().ToString('n');host_id=[Environment]::MachineName;operating_identity=$OperatingIdentity;target_set_digest=$targetDigest;created_at=[DateTimeOffset]::UtcNow.ToString('o');paths=$snapshots}
$m.mac_sha256=Mac $key (ManifestPayload $m);$stamp=[DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssZ');if($PSCmdlet.ShouldProcess($EvidenceRoot,'Create protected audit directory')){New-Item -ItemType Directory -Force $EvidenceRoot|Out-Null;Restrict $EvidenceRoot};$rollback=Join-Path $EvidenceRoot "secret-acl-rollback-$stamp.json";if($PSCmdlet.ShouldProcess($rollback,'Write authenticated rollback manifest')){$m|ConvertTo-Json -Depth 9|Set-Content -LiteralPath $rollback -Encoding utf8}
try{foreach($t in $targets){if($PSCmdlet.ShouldProcess($t,'Replace secret ACL')){Restrict $t;if(-not(Test-Compliant $t $allow)){throw "Post-write ACL verification failed: $t"}}}}
catch{$cause=$_.Exception.Message;$failed=@();foreach($entry in $snapshots){try{Restore $entry;Assert-Restored $entry}catch{$failed+=$entry.path}};if($failed){throw "CRITICAL: ACL transaction failed and rollback could not be verified for: $($failed-join', '). Cause: $cause"};throw "Secret ACL transaction rolled back and verified. Cause: $cause"}
[ordered]@{applied_at=[DateTimeOffset]::UtcNow.ToString('o');run_id=$m.run_id;target_set_digest=$targetDigest;paths=$targets;rollback_manifest=$rollback}|ConvertTo-Json
