[CmdletBinding(SupportsShouldProcess)]
param([string]$BackupRoot='C:\ProgramData\Gbuzz\encrypted-backups',[datetime]$NowUtc=[datetime]::UtcNow,[long]$MaxLocalBytes=100GB,[long]$ReserveBytes=0,[string]$ExcludePath='')
$ErrorActionPreference='Stop';if(-not(Test-Path $BackupRoot)){return};$root=[IO.Path]::GetFullPath($BackupRoot).TrimEnd('\')
$runs=Get-ChildItem -LiteralPath $root -Directory|Where-Object{$_.Name-match'^\d{8}T\d{6}Z-[0-9a-f]{8}$'-and(Test-Path(Join-Path $_.FullName 'COMPLETE'))}|Sort-Object Name -Descending
$parsed=$runs|ForEach-Object{[pscustomobject]@{Item=$_;Time=[datetime]::ParseExact($_.Name.Substring(0,16),'yyyyMMddTHHmmssZ',[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::AssumeUniversal).ToUniversalTime();Bytes=[long]((Get-ChildItem $_.FullName -Recurse -File|Measure-Object Length -Sum).Sum)}}
$keep=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);$parsed|Where-Object{$_.Time-ge$NowUtc.AddHours(-24)}|ForEach-Object{$null=$keep.Add($_.Item.FullName)};$parsed|Where-Object{$_.Time-ge$NowUtc.AddDays(-7)}|Group-Object{$_.Time.ToString('yyyy-MM-dd')}|ForEach-Object{$null=$keep.Add($_.Group[0].Item.FullName)}
$calendar=[Globalization.CultureInfo]::InvariantCulture.Calendar;$parsed|Where-Object{$_.Time-ge$NowUtc.AddDays(-35)}|Group-Object{"$($_.Time.Year)-$($calendar.GetWeekOfYear($_.Time,[Globalization.CalendarWeekRule]::FirstFourDayWeek,[DayOfWeek]::Monday))"}|ForEach-Object{$null=$keep.Add($_.Group[0].Item.FullName)};$parsed|Where-Object{$_.Time-ge$NowUtc.AddMonths(-12)}|Group-Object{$_.Time.ToString('yyyy-MM')}|ForEach-Object{$null=$keep.Add($_.Group[0].Item.FullName)}
$eligible=$parsed|Where-Object{-not$keep.Contains($_.Item.FullName)};foreach($run in $eligible){$path=[IO.Path]::GetFullPath($run.Item.FullName);if(-not$path.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Refusing to prune outside backup root.'};if($PSCmdlet.ShouldProcess($path,'Remove expired encrypted backup')){Remove-Item -LiteralPath $path -Recurse -Force}}
$protectedBytes=[long](($parsed|Where-Object{$keep.Contains($_.Item.FullName)}|Measure-Object Bytes -Sum).Sum);$excluded=if($ExcludePath){[IO.Path]::GetFullPath($ExcludePath).TrimEnd('\')+'\'}else{''};$allBytes=[long]((Get-ChildItem $root -Recurse -File|Where-Object{-not$excluded-or-not$_.FullName.StartsWith($excluded,[StringComparison]::OrdinalIgnoreCase)}|Measure-Object Length -Sum).Sum);$otherBytes=[math]::Max(0,$allBytes-$protectedBytes);if($protectedBytes+$otherBytes+$ReserveBytes-gt$MaxLocalBytes){throw "Required retention points, unclassified data, and requested reserve exceed the local backup bound ($protectedBytes + $otherBytes + $ReserveBytes > $MaxLocalBytes); protected recovery points were not deleted."}
[ordered]@{protected_bytes=$protectedBytes;other_bytes=$otherBytes;reserve_bytes=$ReserveBytes;max_bytes=$MaxLocalBytes;eligible_removed=@($eligible).Count}|ConvertTo-Json -Compress
