[CmdletBinding()]
param([string]$RepoRoot='C:\Gbuzz',[string]$ConfigPath='C:\Gbuzz\config\windows-startup.compose-files.json',[int]$DockerWaitSeconds=300,[int]$ReadinessWaitSeconds=300,[string]$AuditRoot='C:\ProgramData\Gbuzz\startup-audit')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;Import-Module (Join-Path $PSScriptRoot 'ComposePlan.psm1') -Force
$plan=Get-GbuzzComposePlan $RepoRoot $ConfigPath;Push-Location $RepoRoot;try{$config=& docker compose @($plan.Arguments) config --format json|ConvertFrom-Json;if($LASTEXITCODE-ne 0){throw 'Unable to resolve the reviewed Compose plan.'};Assert-GbuzzRequiredServices $plan $config}finally{Pop-Location}
$started=[DateTimeOffset]::UtcNow;New-Item -ItemType Directory -Force $AuditRoot|Out-Null;$audit=Join-Path $AuditRoot ($started.ToString('yyyyMMddTHHmmssZ')+'.json');$result=[ordered]@{started_at=$started.ToString('o');success=$false;docker_wait_seconds=$DockerWaitSeconds;readiness_wait_seconds=$ReadinessWaitSeconds;checks=@()}
try{$deadline=(Get-Date).AddSeconds($DockerWaitSeconds);do{docker info *> $null;if($LASTEXITCODE-eq 0){break};Start-Sleep 5}while((Get-Date)-lt$deadline);if($LASTEXITCODE-ne 0){throw 'Docker daemon did not become ready within the bounded wait.'}
    Push-Location $RepoRoot;try{& docker compose @($plan.Arguments) up -d --no-deps @($plan.RequiredServices);if($LASTEXITCODE-ne 0){throw 'Compose startup failed.'}}finally{Pop-Location};$deadline=(Get-Date).AddSeconds($ReadinessWaitSeconds);$ready=$false
    do{$checks=@();foreach($url in @('http://127.0.0.1:3000/_readiness','http://127.0.0.1:5001/health/ready','http://127.0.0.1:8082/health','http://127.0.0.1:9090/-/ready')){try{$response=Invoke-WebRequest $url -UseBasicParsing -TimeoutSec 5;$checks+=[ordered]@{url=$url;status=$response.StatusCode}}catch{$checks+=[ordered]@{url=$url;status=0}}};$result.checks=$checks;$ready=@($checks|Where-Object{$_.status-ne 200}).Count-eq 0;if(-not$ready){Start-Sleep 5}}while(-not$ready-and(Get-Date)-lt$deadline);if(-not$ready){throw 'Stack readiness did not converge within the bounded wait.'}
    $ids=@(& docker ps -q --filter "label=com.docker.compose.project=$($plan.Project)");if($LASTEXITCODE -ne 0){throw 'Unable to inventory the running Compose project.'};$runtime=@();foreach($id in $ids){$inspect=@(& docker inspect $id|ConvertFrom-Json)[0];$labels=$inspect.Config.Labels;$health='none';if($inspect.State.PSObject.Properties['Health']){$health=[string]$inspect.State.Health.Status};$files=@();$property=$labels.PSObject.Properties['com.docker.compose.project.config_files'];if($property-and$property.Value){$files=@(([string]$property.Value)-split','|ForEach-Object{$_.Trim()}|Where-Object{$_})};$runtime+=[pscustomobject]@{Name=[string]$inspect.Name.TrimStart('/');Service=[string]$labels.'com.docker.compose.service';Status=[string]$inspect.State.Status;Health=$health;Image=[string]$inspect.Config.Image;ImageId=[string]$inspect.Image;ConfigFiles=$files}};$result.runtime=$runtime;Assert-GbuzzRuntimePlan $plan $runtime;$result.success=$true
}catch{$result.error=$_.Exception.Message;throw}finally{$result.finished_at=[DateTimeOffset]::UtcNow.ToString('o');$result|ConvertTo-Json -Depth 6|Set-Content -LiteralPath $audit -Encoding utf8}
