[CmdletBinding()]
param([string]$BindAddress=$env:BUZZ_LAN_BIND_ADDR,[string]$RemoteCidr=$env:BUZZ_LAN_REMOTE_CIDR,[int]$Port=3000,[string]$EnvFixture,[string[]]$ComposeFiles=@('docker-compose.yml','docker-compose.production.yml','docker-compose.production.lock.example.yml','docker-compose.lan.yml'))
$ErrorActionPreference='Stop';Import-Module (Join-Path $PSScriptRoot LanSecurity.psm1) -Force
if(-not$EnvFixture){$EnvFixture=Join-Path (Split-Path -Parent $PSScriptRoot) 'config\lan-compose.synthetic.env'}
if(-not$BindAddress-or-not$RemoteCidr){throw 'BUZZ_LAN_BIND_ADDR and BUZZ_LAN_REMOTE_CIDR are required.'};if(-not(Test-Path -LiteralPath $EnvFixture -PathType Leaf)){throw "Synthetic non-secret Compose fixture missing: $EnvFixture"}
if(-not(Test-GbuzzPrivateIPv4 $BindAddress)-or-not(Test-GbuzzAddressInCidr $BindAddress $RemoteCidr)){throw 'LAN validation failed.'}
$env:BUZZ_LAN_BIND_ADDR=$BindAddress;$env:BUZZ_HTTP_PORT=[string]$Port;$env:BUZZ_ENV_FILE=[IO.Path]::GetFullPath($EnvFixture);$args=@('compose','--env-file',$EnvFixture);foreach($file in $ComposeFiles){if(-not(Test-Path -LiteralPath $file -PathType Leaf)){throw "Compose file missing: $file"};$args+=@('-f',$file)};$args+=@('config','--format','json');$raw=& docker @args;if($LASTEXITCODE-ne0){throw 'Exact production Compose LAN plan failed.'};$plan=$raw|ConvertFrom-Json
$published=@();foreach($service in $plan.services.PSObject.Properties){foreach($binding in @($service.Value.ports)){if($binding){$published+=[pscustomobject]@{service=$service.Name;host_ip=[string]$binding.host_ip;published=[string]$binding.published;target=[string]$binding.target}}}}
$relay=@($published|Where-Object service -eq relay);if($relay.Count-ne1){throw 'Relay must publish exactly one port.'};$binding=$relay[0];if($binding.host_ip-ne$BindAddress-or$binding.published-ne[string]$Port-or$binding.target-ne'3000'){throw 'Resolved relay publication differs from approved binding.'}
$unsafe=@($published|Where-Object{$_.service-ne'relay'-and$_.host_ip-notin@('127.0.0.1','::1')});if($unsafe){throw "Non-relay services publish beyond loopback: $($unsafe.service-join', ')"};$wild=@($published|Where-Object{$_.host_ip-in@('','0.0.0.0','::')});if($wild){throw "Wildcard publication found: $($wild.service-join', ')"}
[ordered]@{verified=$true;compose_files=$ComposeFiles;published_ports=$published;approved_relay="$BindAddress`:$Port";remote_cidr=$RemoteCidr}|ConvertTo-Json -Depth 6
